# syntax=docker/dockerfile:1

FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /bin/worker ./cmd/worker

FROM alpine:3.21
RUN adduser -D -g '' app
USER app
COPY --from=build /bin/worker /usr/local/bin/worker
ENTRYPOINT ["worker"]
