// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    id,
    client_id,
    event_type,
    payload,
    status,
    received_at
) VALUES (
    $1, $2, $3, $4, 'pending', $5
)
RETURNING id, client_id, event_type, payload, status, received_at, processed_at
`

type CreateEventParams struct {
	ID         pgtype.UUID
	ClientID   string
	EventType  string
	Payload    []byte
	ReceivedAt pgtype.Timestamptz
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.ClientID,
		arg.EventType,
		arg.Payload,
		arg.ReceivedAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, client_id, event_type, payload, status, received_at, processed_at
FROM events
WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}
