// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          pgtype.UUID
	ClientID    string
	EventType   string
	Payload     []byte
	Status      string
	ReceivedAt  pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
}
